use sanjay
CREATE TABLE ONLINE(ID INT IDENTITY(1,1),USERNAME VARCHAR(50),PWD VARCHAR(50),SEX VARCHAR(10),DOB DATE,CLG VARCHAR(50),STA VARCHAR(50),IMG VARCHAR(50)); 
SELECT * FROM ONLINE
INSERT INTO ONLINE VALUES('thillaivasan.sanjay@gmail.com','12345','male','22-dec-2014','psg college of technology','Tamilnadu','d:\songs');
CREATE PROCEDURE SP_REGISTER
(
@USERNAME VARCHAR(50),
@PWD VARCHAR(50),
@SEX VARCHAR(10),
@DOB DATE,
@CLG VARCHAR(50),
@STA VARCHAR(50),
@IMG VARCHAR(50)
)
AS 
INSERT INTO ONLINE VALUES(@USERNAME,@PWD,@SEX,@DOB,@CLG,@STA,@IMG)
SELECT * FROM ONLINE
CREATE PROCEDURE SP_LOGIN
(
@USERNAME VARCHAR(50),
@PWD VARCHAR(50)
)
AS SELECT * FROM ONLINE WHERE USERNAME=@USERNAME AND PWD=@PWD 
CREATE PROCEDURE SP_UPDATE
(
@USERNAME VARCHAR(50),
@PWD VARCHAR(50),
@SEX VARCHAR(10),
@DOB DATE,
@CLG VARCHAR(50),
@STA VARCHAR(50),
@IMG VARCHAR(50)
)
AS
UPDATE ONLINE SET USERNAME=@USERNAME,PWD=@PWD,SEX=@SEX,DOB=@DOB,CLG=@CLG,STA=@STA,IMG=@IMG
DROP PROCEDURE SP_REGISTER

